import { ChecklistItem } from '@/lib/constants/home-shopping-data';

export function generateChecklistPDF(
  items: ChecklistItem[],
  checkedItems: Set<string>
): void {
  // Create a simple HTML structure for the checklist
  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>VA Home Shopping Checklist</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
          }
          h1 {
            color: #1e40af;
            border-bottom: 2px solid #1e40af;
            padding-bottom: 10px;
          }
          h2 {
            color: #374151;
            margin-top: 30px;
          }
          .checklist-item {
            margin: 10px 0;
            display: flex;
            align-items: flex-start;
          }
          .checkbox {
            width: 20px;
            height: 20px;
            border: 2px solid #374151;
            margin-right: 10px;
            flex-shrink: 0;
            position: relative;
          }
          .checkbox.checked::after {
            content: '✓';
            position: absolute;
            top: -2px;
            left: 2px;
            font-size: 16px;
            color: #059669;
          }
          .priority {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 12px;
            margin-left: 10px;
          }
          .priority-high {
            background-color: #fee2e2;
            color: #991b1b;
          }
          .priority-medium {
            background-color: #e5e7eb;
            color: #374151;
          }
          .priority-low {
            background-color: #f3f4f6;
            color: #6b7280;
          }
          .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            color: #6b7280;
            font-size: 14px;
          }
        </style>
      </head>
      <body>
        <h1>VA Home Shopping Checklist</h1>
        <p>Use this checklist to track your progress through the VA home buying process.</p>
        
        ${generateCategorySections(items, checkedItems)}
        
        <div class="footer">
          <p>Generated by Ultimate VA Loans • ${new Date().toLocaleDateString()}</p>
          <p>Visit ultimatevaloans.com for more resources</p>
        </div>
      </body>
    </html>
  `;

  // Create a blob and trigger download
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  
  // Create a temporary iframe to print/save as PDF
  const iframe = document.createElement('iframe');
  iframe.style.display = 'none';
  document.body.appendChild(iframe);
  
  iframe.src = url;
  iframe.onload = () => {
    iframe.contentWindow?.print();
    setTimeout(() => {
      document.body.removeChild(iframe);
      URL.revokeObjectURL(url);
    }, 1000);
  };
}

function generateCategorySections(
  items: ChecklistItem[],
  checkedItems: Set<string>
): string {
  const categories = [...new Set(items.map(item => item.category))];
  
  return categories.map(category => {
    const categoryItems = items.filter(item => item.category === category);
    
    return `
      <h2>${category}</h2>
      ${categoryItems.map(item => `
        <div class="checklist-item">
          <div class="checkbox ${checkedItems.has(item.id) ? 'checked' : ''}"></div>
          <div>
            ${item.text}
            <span class="priority priority-${item.priority}">
              ${item.priority.toUpperCase()}
            </span>
          </div>
        </div>
      `).join('')}
    `;
  }).join('');
}